"""empty message

Revision ID: 17d7df7b7117
Revises: b4a5d0006a3c
Create Date: 2022-03-08 19:21:09.291980

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "17d7df7b7117"
down_revision = "b4a5d0006a3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artwork",
        sa.Column("artwork_rate", sa.Integer(), nullable=True),
        schema="vision_sources",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artwork", "artwork_rate", schema="vision_sources")
    # ### end Alembic commands ###
