"""empty message

Revision ID: 8036a1e87a6b
Revises: 3dba6de23158
Create Date: 2022-02-05 02:35:18.786322

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8036a1e87a6b"
down_revision = "3dba6de23158"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("cn", "en", "fr", name="language"),
            server_default="en",
            nullable=False,
        ),
        sa.Column(
            "date_joined",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("admin", "editor", "visitor", name="userrole"),
            server_default="visitor",
            nullable=False,
        ),
        sa.Column(
            "extras", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_email"),
        sa.UniqueConstraint("user_id"),
        schema="vision_sources",
    )
    op.create_unique_constraint(
        None, "artwork", ["artwork_id"], schema="vision_sources"
    )
    op.create_unique_constraint(
        None, "introduction", ["introduction_id"], schema="vision_sources"
    )
    op.drop_column("introduction", "lang", schema="vision_sources")
    op.create_unique_constraint(
        None, "landmark", ["landmark_id"], schema="vision_sources"
    )
    op.add_column(
        "series",
        sa.Column(
            "language",
            sa.Enum("cn", "en", "fr", name="language"),
            server_default="en",
            nullable=False,
        ),
        schema="vision_sources",
    )
    op.create_unique_constraint(
        None, "series", ["series_id"], schema="vision_sources"
    )
    op.drop_column("series", "lang", schema="vision_sources")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "series",
        sa.Column("lang", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="vision_sources",
    )
    op.drop_constraint(None, "series", schema="vision_sources", type_="unique")
    op.drop_column("series", "language", schema="vision_sources")
    op.drop_constraint(
        None, "landmark", schema="vision_sources", type_="unique"
    )
    op.add_column(
        "introduction",
        sa.Column("lang", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="vision_sources",
    )
    op.drop_constraint(
        None, "introduction", schema="vision_sources", type_="unique"
    )
    op.drop_constraint(
        None, "artwork", schema="vision_sources", type_="unique"
    )
    op.drop_table("user", schema="vision_sources")
    # ### end Alembic commands ###
