"""empty message

Revision ID: ad402df20286
Revises: 8036a1e87a6b
Create Date: 2022-02-05 02:57:32.922051

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "ad402df20286"
down_revision = "8036a1e87a6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "introduction",
        sa.Column(
            "language",
            sa.Enum("cn", "en", "fr", name="language"),
            server_default="en",
            nullable=False,
        ),
        schema="vision_sources",
    )
    op.create_unique_constraint(
        None, "user", ["user_id"], schema="vision_sources"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", schema="vision_sources", type_="unique")
    op.drop_column("introduction", "language", schema="vision_sources")
    # ### end Alembic commands ###
