"""empty message

Revision ID: e3911b2fb934
Revises: ad402df20286
Create Date: 2022-02-05 02:58:20.840339

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "e3911b2fb934"
down_revision = "ad402df20286"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
