"""empty message

Revision ID: e731b2aa2436
Revises: f0e77116e401
Create Date: 2022-03-30 22:20:34.244379

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "e731b2aa2436"
down_revision = "f0e77116e401"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity",
        sa.Column("activity_unique_id", sa.String(), nullable=True),
        schema="vision_sources",
    )
    op.create_unique_constraint(
        None, "activity", ["activity_id"], schema="vision_sources"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "activity", schema="vision_sources", type_="unique"
    )
    op.drop_column("activity", "activity_unique_id", schema="vision_sources")
    # ### end Alembic commands ###
