"""empty message

Revision ID: f0e77116e401
Revises: f79569ceb4a7
Create Date: 2022-03-30 17:05:02.967685

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f0e77116e401"
down_revision = "f79569ceb4a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geography(
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "activity_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "activity_name",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "description",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("cover_image", sa.String(), nullable=True),
        sa.Column(
            "extra", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("activity_id"),
        sa.UniqueConstraint("activity_id"),
        schema="vision_sources",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity", schema="vision_sources")
    # ### end Alembic commands ###
