version: '3'
services:

  mongodb:
          hostname: mongodb
          image: mongo:4.0.4
          ports:
            - "27777:27017"
          volumes:     
            - ./mongo:/data/db:rw
          command: mongod --smallfiles --logpath=/dev/null # --quiet
          environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
