version: "3"

dotenv:
  - .env

vars:
  ci:
    sh: "[[ -z $CI ]] && echo 0 || echo 1"

tasks:
  install: PYENV_VERSION=vision pip install -r requirements.test.txt
  serve: uvicorn app:get_app --factory --reload
  migrate_generate: PYENV_VERSION=vision alembic revision --autogenerate
  migrate_apply: PYENV_VERSION=vision  alembic upgrade head
  migrate_rollback: PYENV_VERSION=vision  alembic downgrade -1
  test: |
    PYENV_VERSION=vision \
    VIAFLAGS_USE_ENV_SETTINGS={{.ci}} \
    VIAFLAGS_FILE=flags.test.yml \
    VIAFLAGS_CONTENTS_JSON='' \
    VIAFLAGS_CONTENTS='' \
    NAMESPACE='vianova-test' \
    python3.8 -m py.test \
    -vvv -x -s \
    -W ignore::DeprecationWarning \
    -W ignore::sqlalchemy.exc.SAWarning \
    --cov . \
    --cov-report html:cov_html \
    --junit-xml test-out/report.xml \
    --ff \
    {{.args}} \
    tests/unit/{{.filename}}