version: "3"

dotenv:
  - .env

vars:
  ci:
    sh: "[[ -z $CI ]] && echo 0 || echo 1"

tasks:
  install: PYENV_VERSION=vision pip install -r requirements.test.txt
  serve: uvicorn app:get_app --factory --reload
  migrate_generate: PYENV_VERSION=vision alembic revision --autogenerate
  migrate_apply: PYENV_VERSION=vision  alembic upgrade head
  migrate_rollback: PYENV_VERSION=vision  alembic downgrade -1