version: "3"

dotenv:
  - .env

vars:
  ci:
    sh: "[[ -z $CI ]] && echo 0 || echo 1"

tasks:
  install: PYENV_VERSION=vision pip install -r requirements.test.txt
  serve: uvicorn app:get_app --factory --reload
  migrate_generate: PYENV_VERSION=vision alembic revision --autogenerate
  migrate_apply: PYENV_VERSION=vision  alembic upgrade head
  migrate_rollback: PYENV_VERSION=vision  alembic downgrade -1
  test: |
    PYENV_VERSION=vision \
    VISIONFLAGS_USE_ENV_SETTINGS={{.ci}} \
    VISIONFLAGS_FILE=flags.test.yml \
    VISIONFLAGS_CONTENTS_JSON='' \
    VISIONFLAGS_CONTENTS='' \
    NAMESPACE='vision-test' \
    python3.8 -m py.test \
    -vvv -x -s \
    -W ignore::DeprecationWarning \
    -W ignore::sqlalchemy.exc.SAWarning \
    --cov . \
    --cov-report html:cov_html \
    --junit-xml test-out/report.xml \
    --ff \
    {{.args}} \
    tests/unit/{{.filename}}
  gen:
    - NAMESPACE=test VISIONFLAGS_FILE=flags.test.yml VISION_DEBUG=1 python -m  commands.export_openapi --out-file ../explorer/api/openapi.json
    - openapi-generator  generate -g typescript-axios -i ../explorer/api/openapi.json --skip-validate-spec -o ../explorer/api
    - cp -r ../explorer/api ../louvre/src/
  artwork_search_index: PYENV_VERSION=vision python -m commands.artwork_search_index
  detect_poc: PYENV_VERSION=vision python -m commands.detect_poc
  recalculate_descriptors: PYENV_VERSION=vision python -m commands.recalculate_descriptors
  fetch_activities: PYENV_VERSION=vision python -m commands.fetch_activities
  a2g: PYENV_VERSION=vision python -m commands.activities_to_geometry
  g2gi: PYENV_VERSION=vision python -m commands.geojson_to_geometry_items
