"""empty message

Revision ID: 578019668013
Revises: 7c8945304abb
Create Date: 2021-12-08 00:23:28.752761

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "578019668013"
down_revision = "7c8945304abb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series",
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "series_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column("series_name", sa.String(), nullable=False),
        sa.Column("landmark_id", sa.BigInteger(), nullable=False),
        sa.Column("cover_image", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["landmark_id"],
            ["vision_sources.landmark.landmark_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("series_id"),
        sa.UniqueConstraint("series_id"),
        schema="vision_sources",
    )
    op.create_index(
        op.f("ix_vision_sources_series_landmark_id"),
        "series",
        ["landmark_id"],
        unique=False,
        schema="vision_sources",
    )
    op.create_table(
        "introduction",
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "introduction_id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("introduction_name", sa.String(), nullable=False),
        sa.Column("series_id", sa.BigInteger(), nullable=False),
        sa.Column("artwork_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "introduction",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["vision_sources.artwork.artwork_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["vision_sources.landmark.landmark_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("introduction_id"),
        sa.UniqueConstraint("introduction_id"),
        schema="vision_sources",
    )
    op.create_index(
        op.f("ix_vision_sources_introduction_artwork_id"),
        "introduction",
        ["artwork_id"],
        unique=False,
        schema="vision_sources",
    )
    op.create_index(
        op.f("ix_vision_sources_introduction_series_id"),
        "introduction",
        ["series_id"],
        unique=False,
        schema="vision_sources",
    )
    op.create_unique_constraint(
        None, "artwork", ["artwork_id"], schema="vision_sources"
    )
    op.create_unique_constraint(
        None, "landmark", ["landmark_id"], schema="vision_sources"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "landmark", schema="vision_sources", type_="unique"
    )
    op.drop_constraint(
        None, "artwork", schema="vision_sources", type_="unique"
    )
    op.drop_index(
        op.f("ix_vision_sources_introduction_series_id"),
        table_name="introduction",
        schema="vision_sources",
    )
    op.drop_index(
        op.f("ix_vision_sources_introduction_artwork_id"),
        table_name="introduction",
        schema="vision_sources",
    )
    op.drop_table("introduction", schema="vision_sources")
    op.drop_index(
        op.f("ix_vision_sources_series_landmark_id"),
        table_name="series",
        schema="vision_sources",
    )
    op.drop_table("series", schema="vision_sources")
    # ### end Alembic commands ###
