"""empty message

Revision ID: 5ebc4fc2da92
Revises: 6a472c6e86ad
Create Date: 2022-03-24 22:26:37.088964

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "5ebc4fc2da92"
down_revision = "6a472c6e86ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "introduction",
        "artwork_id",
        existing_type=sa.BIGINT(),
        nullable=True,
        schema="vision_sources",
    )
    op.drop_constraint(
        "introduction_artwork_id_fkey",
        "introduction",
        schema="vision_sources",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "introduction",
        "artwork",
        ["artwork_id"],
        ["artwork_id"],
        source_schema="vision_sources",
        referent_schema="vision_sources",
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.alter_column(
        "series",
        "landmark_id",
        existing_type=sa.BIGINT(),
        nullable=True,
        schema="vision_sources",
    )
    op.drop_constraint(
        "series_landmark_id_fkey",
        "series",
        schema="vision_sources",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "series",
        "landmark",
        ["landmark_id"],
        ["landmark_id"],
        source_schema="vision_sources",
        referent_schema="vision_sources",
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "series", schema="vision_sources", type_="foreignkey"
    )
    op.create_foreign_key(
        "series_landmark_id_fkey",
        "series",
        "landmark",
        ["landmark_id"],
        ["landmark_id"],
        source_schema="vision_sources",
        referent_schema="vision_sources",
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "series",
        "landmark_id",
        existing_type=sa.BIGINT(),
        nullable=False,
        schema="vision_sources",
    )
    op.drop_constraint(
        None, "introduction", schema="vision_sources", type_="foreignkey"
    )
    op.create_foreign_key(
        "introduction_artwork_id_fkey",
        "introduction",
        "artwork",
        ["artwork_id"],
        ["artwork_id"],
        source_schema="vision_sources",
        referent_schema="vision_sources",
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "introduction",
        "artwork_id",
        existing_type=sa.BIGINT(),
        nullable=False,
        schema="vision_sources",
    )
    # ### end Alembic commands ###
