"""empty message

Revision ID: 6a472c6e86ad
Revises: 6dbae7fc7cf8
Create Date: 2022-03-08 19:24:42.159758

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "6a472c6e86ad"
down_revision = "6dbae7fc7cf8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artwork",
        sa.Column("artwork_rate", sa.Integer(), nullable=True),
        schema="vision_sources",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artwork", "artwork_rate", schema="vision_sources")
    # ### end Alembic commands ###
