"""empty message

Revision ID: 6dbae7fc7cf8
Revises: 6509f7de514b
Create Date: 2022-02-08 22:31:16.008505

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6dbae7fc7cf8"
down_revision = "6509f7de514b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "introduction",
        sa.Column(
            "language",
            sa.Enum("cn", "en", "fr", name="language"),
            server_default="en",
            nullable=False,
        ),
        schema="vision_sources",
    )
    op.add_column(
        "series",
        sa.Column("author_id", postgresql.UUID(), nullable=False),
        schema="vision_sources",
    )
    op.create_index(
        op.f("ix_vision_sources_series_author_id"),
        "series",
        ["author_id"],
        unique=False,
        schema="vision_sources",
    )
    op.create_foreign_key(
        None,
        "series",
        "user",
        ["author_id"],
        ["user_id"],
        source_schema="vision_sources",
        referent_schema="vision_sources",
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        None, "user", ["user_id"], schema="vision_sources"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", schema="vision_sources", type_="unique")
    op.drop_constraint(
        None, "series", schema="vision_sources", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_vision_sources_series_author_id"),
        table_name="series",
        schema="vision_sources",
    )
    op.drop_column("series", "author_id", schema="vision_sources")
    op.drop_column("introduction", "language", schema="vision_sources")
    # ### end Alembic commands ###
