"""empty message

Revision ID: 8da149d027fd
Revises: 578019668013
Create Date: 2021-12-08 00:29:24.441716

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "8da149d027fd"
down_revision = "578019668013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "introduction", ["introduction_id"], schema="vision_sources"
    )
    op.drop_constraint(
        "introduction_series_id_fkey",
        "introduction",
        schema="vision_sources",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "introduction",
        "series",
        ["series_id"],
        ["series_id"],
        source_schema="vision_sources",
        referent_schema="vision_sources",
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        None, "series", ["series_id"], schema="vision_sources"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "series", schema="vision_sources", type_="unique")
    op.drop_constraint(
        None, "introduction", schema="vision_sources", type_="foreignkey"
    )
    op.create_foreign_key(
        "introduction_series_id_fkey",
        "introduction",
        "landmark",
        ["series_id"],
        ["landmark_id"],
        source_schema="vision_sources",
        referent_schema="vision_sources",
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        None, "introduction", schema="vision_sources", type_="unique"
    )
    # ### end Alembic commands ###
