"""empty message

Revision ID: 9f330fcdf066
Revises: 06a49c7010fc
Create Date: 2022-04-04 00:02:25.988739

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "9f330fcdf066"
down_revision = "06a49c7010fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity",
        sa.Column("activity_unique_id", sa.String(), nullable=True),
        schema="vision_sources",
    )
    op.create_unique_constraint(
        None, "activity", ["activity_id"], schema="vision_sources"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "activity", schema="vision_sources", type_="unique"
    )
    op.drop_column("activity", "activity_unique_id", schema="vision_sources")
    # ### end Alembic commands ###
