"""empty message

Revision ID: c6a70cf62724
Revises: de1fd13ebe9b
Create Date: 2022-05-24 00:15:40.268974

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "c6a70cf62724"
down_revision = "de1fd13ebe9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "geometry", ["geometry_id"], schema="vision_sources"
    )
    op.drop_column("geometry", "self_link", schema="vision_sources")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "geometry",
        sa.Column(
            "self_link", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        schema="vision_sources",
    )
    op.drop_constraint(
        None, "geometry", schema="vision_sources", type_="unique"
    )
    # ### end Alembic commands ###
