"""empty message

Revision ID: de1fd13ebe9b
Revises: 379a3a07e65f
Create Date: 2022-05-03 22:16:00.502101

"""
import geoalchemy2  # noqa
from alembic import op
import sqlalchemy as sa  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de1fd13ebe9b"
down_revision = "379a3a07e65f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geometry",
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geography(
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "geometry_id", sa.BigInteger(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "geometry_name",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("geometry_type", sa.String(), nullable=True),
        sa.Column(
            "description",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "extra", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "display", sa.Boolean(), server_default="TRUE", nullable=False
        ),
        sa.Column("self_link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("geometry_id"),
        sa.UniqueConstraint("geometry_id"),
        schema="vision_sources",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("geometry", schema="vision_sources")
    # ### end Alembic commands ###
